workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-coverage

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"
  latest:
    image: docker
    storage_driver: overlay
    repo: plugins/coverage
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push
  develop:
    image: docker
    storage_driver: overlay
    repo: plugins/coverage
    tags: [ "develop" ]
    when:
      branch: develop
      event: push

plugin:
  name: Coverage
  desc: Aggregate and publish coverage reports
  type: publish
  image: plugins/coverage
  labels:
    - coverage
    - reporting
    - lcov
    - simplecov
