workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-coverage

pipeline:
  test:
    image: golang:1.7
    environment:
      - CGO_ENABLED=0
    commands:
      - go get
      - go vet
      - |
        for pkg in $(go list ./... | grep -v /vendor/)
        do  
          go test -cover -coverprofile $GOPATH/src/$pkg/coverage.out $pkg || exit 1
        done
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  coverage:
    image: plugins/coverage
    server: https://aircover.co
    pattern: coverage.out

  latest:
    image: plugins/docker
    repo: plugins/coverage
    tags: [ "latest", "1.1", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Coverage
  desc: Aggregate and publish coverage reports
  type: publish
  image: plugins/coverage
  labels:
    - coverage
    - reporting
    - lcov
    - simplecov
