workspace:
  base: /go

pipeline:
  test:
    image: golang:1.7
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  coverage:
    image: plugins/coverage
    server: https://aircover.co
    pattern: coverage.out

  latest:
    image: plugins/docker
    repo: plugins/coverage
    tags: [ "latest", "1.1", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Coverage
  desc: Aggregate and publish coverage reports
  type: publish
  image: plugins/coverage
  labels:
    - coverage
    - reporting
    - lcov
    - simplecov
