workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-coverage

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - |
        for line in $(go list ./... | grep -v /vendor/)
        do  
          name=$(basename "$line")
          go test "$line" -cover -coverprofile=coverage-"$name".out
        done
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: docker
    repo: plugins/coverage
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Coverage
  desc: Aggregate and publish coverage reports
  type: publish
  image: plugins/coverage
  labels:
    - coverage
    - reporting
    - lcov
    - simplecov
