workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-coverage

pipeline:
  test:
    image: golang:1.6
    commands:
      - make vet
      - make build
      - make test
  # coverage:
  #   when:
  #     branch: master
  #     event: push
  latest:
    image: docker
    storage_driver: overlay
    repo: plugins/coverage
    tags: [ "latest", "0.5" ]
    when:
      branch: master
      event: push
  develop:
    image: docker
    storage_driver: overlay
    repo: plugins/coverage
    tags: [ "develop" ]
    when:
      branch: develop
      event: push

plugin:
  name: Coverage
  desc: Aggregate and publish coverage reports
  type: publish
  image: plugins/coverage
  labels:
    - coverage
    - reporting
    - lcov
    - simplecov
