# escape=`
FROM plugins/base:windows-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Coverage" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release\drone-coverage.exe c:\drone-coverage.exe
ENTRYPOINT [ "c:\\drone-coverage.exe" ]
CMD ["publish"]
